"""added email column

Revision ID: 65d437f20fe3
Revises: 3bd87c56ded8
Create Date: 2025-10-18 15:39:15.049458

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '65d437f20fe3'
down_revision: Union[str, Sequence[str], None] = '3bd87c56ded8'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('updateworkout', sa.Column('email', sa.String(length=255), nullable=True))
    op.create_index(op.f('ix_updateworkout_email'), 'updateworkout', ['email'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_updateworkout_email'), table_name='updateworkout')
    op.drop_column('updateworkout', 'email')
    # ### end Alembic commands ###
